[ci]
runner = "codefloe-global"
runtime = "nix"
step_runners = { cargo-clippy = "atlas-nix-trusted", cargo-doc = "atlas-nix-trusted", cargo-fmt = "atlas-nix-trusted", cargo-package = "atlas-nix-trusted", cargo-test = "atlas-nix-trusted", nix-check = "atlas-nix-trusted", quality-tools = "atlas-nix-trusted" }
publish_crates = true
provider = "crow"
platform = "forgejo"

[ci.pages]
repo = "caniko/visual-rubric"
canonical_domain = "visual-rubric.tartanoglu.com"
