[ci]
runner = "ubuntu-24.04"
runtime = "nix"
step_runners = { cargo-clippy = "ubuntu-24.04", cargo-doc = "ubuntu-24.04", cargo-fmt = "ubuntu-24.04", cargo-package = "ubuntu-24.04", cargo-test = "ubuntu-24.04", nix-check = "ubuntu-24.04", quality-tools = "ubuntu-24.04" }
publish_crates = true
provider = "actions"
platform = "github"
all_features = false

[ci.pages]
repo = "caniko/visual-rubric"
canonical_domain = "visual-rubric.tartanoglu.com"
